[workspace]
members = [
    "crates/warp-demo",
    "crates/wasmedge-demo",
    "crates/wasmtime-demo",
    "crates/pyo3-demo",
    "crates/actix-web-demo"
]

[workspace.dependencies]
anyhow = "1.0.44"

